### ISSUE TITLE
Spring 4

### ISSUE THREAD

**Issue by waynn** [nathan-alden-sr/stardew-valley#15]
I wrote this in the closed PR but realized it was probably better as an issue. 

1. If you're on that path, you don't need to buy more Copper Ore since you got some the day before already, right?
2. You have a comment to Skip to The Beach section but it's the section right after.
3. Technically you don't need to craft a chest since you can just bring the Beach chest => the Mountain. I actually got confused by this in the original guide, why I needed two more chests since I was going to pick one up from The Beach on either Spring 3 or 4.
4. The amount of bait you can buy at this point is usually over 1k because you have Angler and you're selling the Catfish so should probably emphasize that you only really need 400-500. I ended up buying up to 550, will see how it goes.

**Comment by nathan-alden-sr** [comment]
> I wrote this in the closed PR but realized it was probably better as an issue.
> 
>     1. If you're on that path, you don't need to buy more Copper Ore since you got some the day before already, right?

The problem is there are effectively two paths that span two days, and the day-based layout of the guide makes it harder to communicate that. I tried to be very precise in the exact steps to take since early Spring really leaves no margin for error.

The Copper Ore purchase is skipped on Spring 3 if you have 80 Bait and a Copper Ore. Spring 4's _The Beach_ section says "If you ~~received~~ (I changed this to "acquired") a Copper Ore..." so that the reader can account for the possibility.

>     2. You have a comment to Skip to The Beach section but it's the section right after.

I fixed the Beach/Mountain confusion you referenced. It was certainly a mess.

>     3. Technically you don't need to craft a chest since you can just bring the Beach chest => the Mountain. I actually got confused by this in the original guide, why I needed two more chests since I was going to pick one up from The Beach on either Spring 3 or 4.

Fixed as well.

>     4. The amount of bait you can buy at this point is usually over 1k because you have Angler and you're selling the Catfish so should probably emphasize that you only really need 400-500. I ended up buying up to 550, will see how it goes.

I have noticed on several of my playthroughs that it's easy to buy too much bait. I've refined the guidance.

Let me know if https://github.com/nathan-alden-sr/stardew-valley/commit/486c2c073f0c2cf5bf76161c5f4cc7bf14d734b6 fixes these issues for you. If so, feel free to close the issue.

Thanks as usual. 👍

**Comment by waynn** [comment]
Makes sense! I ended up having 3k gold left so had to explicitly go into the Farmhouse before 2am so as not to take the penalty.
