### ISSUE TITLE
Spreadsheet calcluation for second Kale

### ISSUE THREAD

**Issue by waynn** [nathan-alden-sr/stardew-valley#28]
So the row that it's checking for is this `Farming XP by Spring 19`, but technically, shouldn't it be looking at what your XP is by Spring 27 instead? Because if you have Rice (or other crops) coming in between the 19th and 27th, it's not going to factor into that calculation? (Though I get that there's possibly some circular dependency if you do the 27th)

**Comment by nathan-alden-sr** [comment]
Interesting. I hadn't considered this, but I actually think both the _Y1-Sp10_ and _Y1-Sp18_ tabs should be changed to _Farming XP by Spring 27_. Why not? Any crops being tracked--like Bean Starters, Cauliflower, Mixed Seeds, Rice Shoots--might affect the XP calculations all the way to Spring 27 so on a particular day the algorithm should know how much XP to expect by the end. Otherwise, one will end up overpurchasing Kale Seeds.

Great catch. Thanks!

https://github.com/nathan-alden-sr/stardew-valley/commit/01db81e5eb9699a7c6eb7b9f65d7481e714c5255
